// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/classes" | "/admin/families" | "/admin/paces" | "/admin/schedules" | "/admin/settings" | "/admin/users" | "/calendar" | "/dashboard" | "/groups" | "/login" | "/student/assignments" | "/student/calendar" | "/student/classes" | "/student/classes/[classId]" | "/student/dashboard" | "/student/files" | "/student/grades" | "/student/meetings" | "/student/messages" | "/student/notifications" | "/student/paces" | "/student/schedule" | "/teacher/assignments" | "/teacher/calendar" | "/teacher/classes" | "/teacher/classes/[classId]" | "/teacher/dashboard" | "/teacher/files" | "/teacher/gcr" | "/teacher/grades" | "/teacher/meetings" | "/teacher/messages" | "/teacher/notifications" | "/teacher/paces" | "/teacher/schedule"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/classes": {}
  "/admin/families": {}
  "/admin/paces": {}
  "/admin/schedules": {}
  "/admin/settings": {}
  "/admin/users": {}
  "/calendar": {}
  "/dashboard": {}
  "/groups": {}
  "/login": {}
  "/student/assignments": {}
  "/student/calendar": {}
  "/student/classes": {}
  "/student/classes/[classId]": { "classId": string; }
  "/student/dashboard": {}
  "/student/files": {}
  "/student/grades": {}
  "/student/meetings": {}
  "/student/messages": {}
  "/student/notifications": {}
  "/student/paces": {}
  "/student/schedule": {}
  "/teacher/assignments": {}
  "/teacher/calendar": {}
  "/teacher/classes": {}
  "/teacher/classes/[classId]": { "classId": string; }
  "/teacher/dashboard": {}
  "/teacher/files": {}
  "/teacher/gcr": {}
  "/teacher/grades": {}
  "/teacher/meetings": {}
  "/teacher/messages": {}
  "/teacher/notifications": {}
  "/teacher/paces": {}
  "/teacher/schedule": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
