// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/admin/classes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/classes">> = Specific
  const handler = {} as typeof import("../../app/admin/classes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/families/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/families">> = Specific
  const handler = {} as typeof import("../../app/admin/families/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/paces/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/paces">> = Specific
  const handler = {} as typeof import("../../app/admin/paces/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/schedules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/schedules">> = Specific
  const handler = {} as typeof import("../../app/admin/schedules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../app/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/groups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/groups">> = Specific
  const handler = {} as typeof import("../../app/groups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/assignments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/assignments">> = Specific
  const handler = {} as typeof import("../../app/student/assignments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/calendar">> = Specific
  const handler = {} as typeof import("../../app/student/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/classes/[classId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/classes/[classId]">> = Specific
  const handler = {} as typeof import("../../app/student/classes/[classId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/classes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/classes">> = Specific
  const handler = {} as typeof import("../../app/student/classes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/dashboard">> = Specific
  const handler = {} as typeof import("../../app/student/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/files/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/files">> = Specific
  const handler = {} as typeof import("../../app/student/files/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/grades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/grades">> = Specific
  const handler = {} as typeof import("../../app/student/grades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/meetings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/meetings">> = Specific
  const handler = {} as typeof import("../../app/student/meetings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/messages">> = Specific
  const handler = {} as typeof import("../../app/student/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/notifications">> = Specific
  const handler = {} as typeof import("../../app/student/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/paces/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/paces">> = Specific
  const handler = {} as typeof import("../../app/student/paces/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/schedule">> = Specific
  const handler = {} as typeof import("../../app/student/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/teacher/assignments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/assignments">> = Specific
  const handler = {} as typeof import("../../app/teacher/assignments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/teacher/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/calendar">> = Specific
  const handler = {} as typeof import("../../app/teacher/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/teacher/classes/[classId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/classes/[classId]">> = Specific
  const handler = {} as typeof import("../../app/teacher/classes/[classId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/teacher/classes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/classes">> = Specific
  const handler = {} as typeof import("../../app/teacher/classes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/teacher/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/dashboard">> = Specific
  const handler = {} as typeof import("../../app/teacher/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/teacher/files/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/files">> = Specific
  const handler = {} as typeof import("../../app/teacher/files/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/teacher/gcr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/gcr">> = Specific
  const handler = {} as typeof import("../../app/teacher/gcr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/teacher/grades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/grades">> = Specific
  const handler = {} as typeof import("../../app/teacher/grades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/teacher/meetings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/meetings">> = Specific
  const handler = {} as typeof import("../../app/teacher/meetings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/teacher/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/messages">> = Specific
  const handler = {} as typeof import("../../app/teacher/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/teacher/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/notifications">> = Specific
  const handler = {} as typeof import("../../app/teacher/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/teacher/paces/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/paces">> = Specific
  const handler = {} as typeof import("../../app/teacher/paces/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/teacher/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/schedule">> = Specific
  const handler = {} as typeof import("../../app/teacher/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
