"use client";

import { useEffect, useState } from "react";
import type { TeacherClassDetail } from "@homeschool/shared";
import { scheduleApi } from "@/features/schedules/schedule-api";

export function TeacherClassDetailV1({ classId }: { classId: string }) {
  const [detail, setDetail] = useState<TeacherClassDetail | null>(null); const [message, setMessage] = useState("Cargando clase…");
  useEffect(() => { scheduleApi.teacher.classDetail(classId).then((item) => { setDetail(item); setMessage(""); }).catch(() => setMessage("La clase no existe o no está asignada a tu cuenta.")); }, [classId]);
  if (!detail) return <div className="p-8 text-sm text-slate-500">{message}</div>;
  return <div className="space-y-6 p-5 lg:p-8"><section className="rounded-xl p-6 text-white" style={{ backgroundColor: detail.color ?? "#191970" }}><p className="text-xs font-bold uppercase tracking-wider text-white/65">{detail.code} · {detail.gradeLevel?.name}</p><h2 className="mt-2 text-3xl font-semibold">{detail.name}</h2><p className="mt-2 text-sm text-white/75">{detail.description || "Clase académica activa"}</p></section><div className="grid gap-6 xl:grid-cols-3"><section className="rounded-xl border bg-white p-5"><h3 className="font-semibold text-[#191970]">Materias asignadas</h3><div className="mt-3 space-y-3">{detail.subjects.map((subject) => <article key={subject.id} className="rounded-lg bg-[#f6f8fc] p-3"><p className="text-xs font-bold text-[#078cc5]">{subject.shortName}</p><p className="mt-1 font-semibold text-[#191970]">{subject.name}</p></article>)}</div></section><section className="rounded-xl border bg-white p-5"><h3 className="font-semibold text-[#191970]">Alumnos ({detail.students.length})</h3><div className="mt-3 divide-y">{detail.students.map((student) => <div key={student.id} className="py-3"><p className="text-sm font-semibold text-slate-700">{student.displayName}</p><p className="text-xs text-slate-400">{student.email}</p></div>)}</div></section><section className="rounded-xl border bg-white p-5"><h3 className="font-semibold text-[#191970]">Encuentros</h3><div className="mt-3 space-y-3">{detail.bookings.map((booking) => <article key={booking.id} className="rounded-lg bg-[#f6f8fc] p-3"><p className="text-sm font-semibold text-[#191970]">{booking.studentName}</p><p className="mt-1 text-xs text-slate-500">{booking.scheduledDate} · {booking.startTime}</p><b className="mt-2 block text-[10px] text-[#078cc5]">{booking.status}</b></article>)}{!detail.bookings.length ? <p className="text-sm text-slate-500">No hay encuentros para esta clase.</p> : null}</div></section></div></div>;
}
