"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import type { StudentClassDetail } from "@homeschool/shared";
import { scheduleApi } from "@/features/schedules/schedule-api";

export function StudentClassDetailV1({ classId }: { classId: string }) {
  const [detail, setDetail] = useState<StudentClassDetail | null>(null); const [message, setMessage] = useState("Cargando clase…");
  useEffect(() => { scheduleApi.student.classDetail(classId).then((item) => { setDetail(item); setMessage(""); }).catch(() => setMessage("La clase no existe o no está asignada a tu cuenta.")); }, [classId]);
  if (!detail) return <div className="p-8 text-sm text-slate-500">{message}</div>;
  return <div className="space-y-6 p-5 lg:p-8"><section className="rounded-xl p-6 text-white" style={{ backgroundColor: detail.color ?? "#191970" }}><p className="text-xs font-bold uppercase tracking-wider text-white/65">{detail.code} · {detail.gradeLevel?.name}</p><h2 className="mt-2 text-3xl font-semibold">{detail.name}</h2><p className="mt-2 text-sm text-white/75">{detail.description || "Clase académica activa"}</p></section><div className="grid gap-6 xl:grid-cols-[1fr_22rem]"><section className="space-y-4"><h3 className="text-lg font-semibold text-[#191970]">Materias</h3>{detail.subjects.map((subject) => { const progress = detail.paceProgress.filter((item) => item.classSubjectId === subject.id); return <article key={subject.id} className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold" style={{ color: subject.color ?? "#078cc5" }}>{subject.shortName}</p><h4 className="mt-1 font-semibold text-[#191970]">{subject.name}</h4></div><Link href="/student/meetings" className="secondary">Solicitar encuentro</Link></div><p className="mt-3 text-xs text-slate-500">Profesor: {subject.teachers.map((item) => item.teacherName).join(", ") || "Sin asignar"}</p><div className="mt-4 flex flex-wrap gap-2">{progress.map((pace) => <span key={pace.recordId} className={`rounded px-3 py-2 text-xs font-bold ${pace.status === "COMPLETED" ? "bg-emerald-100 text-emerald-700" : pace.status === "CURRENT" ? "bg-blue-100 text-blue-700" : "bg-slate-100 text-slate-500"}`}>PACE {pace.paceNumber}{pace.score != null ? ` · ${pace.score}` : ""}</span>)}{!progress.length ? <span className="text-xs text-slate-500">Los PACEs aparecerán al activar el periodo académico.</span> : null}</div></article>; })}</section><aside className="space-y-4"><section className="rounded-xl border bg-white p-5"><h3 className="font-semibold text-[#191970]">Profesores</h3>{detail.teachers.map((teacher) => <div key={teacher.id} className="mt-3"><p className="text-sm font-semibold text-slate-700">{teacher.displayName}</p><p className="text-xs text-slate-400">{teacher.email}</p></div>)}</section><section className="rounded-xl border bg-white p-5"><h3 className="font-semibold text-[#191970]">Bloques semanales</h3><div className="mt-3 space-y-2">{detail.scheduleBlocks.map((block) => <p key={block.id} className="rounded bg-[#f6f8fc] p-2 text-xs"><b>{block.weekday}</b> · {block.subjectName}</p>)}{!detail.scheduleBlocks.length ? <p className="text-sm text-slate-500">Sin bloques publicados.</p> : null}</div></section></aside></div></div>;
}
